id = "tera"
name = "Tera"
description = "Tera support."
version = "1.2.0"
schema_version = 1
authors = ["uncenter"]
repository = "https://github.com/uncenter/zed-tera"

[grammars.tera]
repository = "https://github.com/uncenter/tree-sitter-tera"
commit = "e8d679a29c03e64656463a892a30da626e19ed8e"
