id = "tera"
name = "Tera"
description = "Tera support."
version = "0.0.1"
schema_version = 1
authors = ["uncenter"]
repository = "https://github.com/uncenter/zed-tera"

[grammars.tera]
repository = "https://github.com/uncenter/tree-sitter-tera"
commit = "93b9790d2dbee93f2cd3e9f69396a14331175239"
