name = "Tera (TOML)"
grammar = "tera"
path_suffixes = ["toml.tera"]
brackets = [
    { start = "{%", end = "%}", close = true, newline = true },
    { start = "{{", end = "}}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "`", end = "`", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "{#", end = "#}", close = true, newline = false },
]
tab_size = 2
